# -*- coding: utf-8 -*-
"""LR API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvriatVKr_Zkck6vGeCllC-X1epKW9Uk
"""


# Importación librerías
import pandas as pd
from sklearn.linear_model import LinearRegression
import joblib
import sys
import os
from sklearn.model_selection import train_test_split

# Carga de datos de archivo .csv
dataTraining = pd.read_csv('https://raw.githubusercontent.com/davidzarruk/MIAD_ML_NLP_2025/main/datasets/dataTrain_Spotify.csv')
dataTesting = pd.read_csv('https://raw.githubusercontent.com/davidzarruk/MIAD_ML_NLP_2025/main/datasets/dataTest_Spotify.csv', index_col=0)

# Importación de librerías

selected_features = [
    'acousticness',
    'danceability',
    'energy',
    'loudness',
    'instrumentalness',

]

X = dataTraining[selected_features]
y = dataTraining['popularity']

# División en entrenamiento (80%) y prueba (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# Función para evaluar el modelo
def evaluar_modelo(nombre_modelo, modelo, X_test, y_test):
    y_pred = modelo.predict(X_test)
    return y_pred

# 1. Modelo Linear Regressor
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
evaluar_modelo("Linear Regression", lr_model, X_test, y_test)
